[package]
name = "pdf_to_text"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "pdf_to_text"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
poppler-rs = "0.19.0"
